---
- name: configure cobbler for the exascaler
  hosts: cobbler
  tags: cobbler
  roles:
    - cobbler

- name: configure boot settings on mds and oss before install
  hosts: cobbler
  tags: boot
  roles:
    - boot

- name: install DDN and configure the exascaler
  hosts: exsc
  tags: exascaler
  roles:
    - ddn
    - mds
    - oss
