---
- name: confirm netboot is enabled for all mds and oss servers in cobbler
  command: "cobbler system edit
            --name={{ item }}
 	    --netboot-enabled=true"
  register: result
  with_items: groups.exsc

- name: set PXE as first boot device on mds and oss servers
  command: ipmitool -H {{ item }} -U root -P calvin chassis bootdev pxe
  with_items: groups['exsc-ipmi']

- name: sync changes for cobbler if systems added
  command: cobbler sync
  when: result.changed
