---
- name: mount DDN iso
  mount: name={{ ddn_iso_path_mnt }} src={{ ddn_iso_path }} fstype=iso9660 opts=ro,loop state=mounted

- name: check if cobbler distro exists
  command: cobbler distro list
  register: result
  failed_when: 
    - "'{{ ddn_image_name }}' in result.stdout"
  ignore_errors: true
  no_log: true

- name: remove existing image 
  command: cobbler distro remove --name {{ ddn_image_name }} --recursive
  when: result.failed

- name: import DDN iso to cobbler
  command: "cobbler import 
  	    --name={{ ddn_image_name }}
	    --arch=x86_64
	    --path={{ ddn_iso_path_mnt }}
	    --available-as={{ ddn_iso_path_web }}"
  register: result
  failed_when: 
    - "'TASK COMPLETE' not in result.stdout"

- name: sync changes for cobbler
  command: cobbler sync
  when: result.changed
