---
- name: add mds and oss systems to cobbler inventory
  command: "cobbler system add 
  	    --name={{ item }} 
	    --profile={{ ddn_image_name }}
	    --hostname={{ item }} 
	    --mac={{ hostvars[item]['interfaces'][hostvars[item]['primary_interface']]['mac'] }} 
	    --ip-address={{ hostvars[item]['interfaces'][hostvars[item]['primary_interface']]['ip'] }} 
	    --interface={{ hostvars[item]['interfaces'][hostvars[item]['primary_interface']]['name'] }} 
	    --kickstart={{ ddn_ks_path }}
            creates=/var/lib/cobbler/config/systems.d/{{ item }}.json"
  register: result
  with_items: groups.exsc

- name: sync changes for cobbler if systems added
  command: cobbler sync
  when: result.changed
